config/routes.rb
Rails.application.routes.draw do
  devise_for :students, controllers: {
    sessions: 'students/sessions',
    passwords: 'students/passwords',
    confirmations: 'students/confirmations',
    unlocks: 'students/unlocks',
    registrations: 'students/registrations'
  }
  
  root to: 'client_backoffice/home#index'

  # Paths Authenticate
  namespace 'client_backoffice', path: 'auth' do
    resources :transactions, only: %i[new create index]
    put 'transactions', to: 'transactions#index'
  end
end

app/views/layouts/_sidemenu.html.erb
<aside class="left-sidebar">
  <!-- Sidebar scroll-->
  <div class="slimScrollDiv">
    <!-- Sidebar navigation-->
    <div class="scroll-sidebar">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">
          <span>
            <h2>UECE BANK</h2>
          </span>
        </a>
      </div>
      <nav class="sidebar-nav active">
        <ul id="sidebarnav" class="in">
          <li>
            <a href="" class="waves-effect"><b>Nº Conta: <%= current_student.number_account %></b></a>
          </li>
          <li>
            <a href="/" class="waves-effect"><i class="fa fa-bar-chart-o m-r-10" aria-hidden="true"></i>Dashboard</a>
          </li>
          <li>
            <%=  link_to client_backoffice_transactions_path, class: "waves-effect"  do %>
              <i class="fa fa-money m-r-10" aria-hidden="true"></i>Extrato
            <%end%>
          </li>
          <li>
            <%=  link_to new_client_backoffice_transaction_path, class: "waves-effect"  do %>
              <i class="fa fa-table m-r-10" aria-hidden="true"></i>Transferência
            <%end%>
          </li>
        </ul>
        <p class="navbar-text">
          <% if student_signed_in? %>
            <%= link_to "Logout", destroy_student_session_path, method: :delete, class: "waves-effect" %>
          <%end%>
        </p>
      </nav>
    </div>
  </div>
</aside>

app/views/layouts/application.html.erb
<% if student_signed_in? %>
  <html>
    <head>
      <title>UECE BANK SECURITY LTDA</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>

    <body class="fix-header fix-sidebar card-no-border">
      <div id="main-wrapper">
          <%= render 'layouts/sidemenu' %>
          <div class="page-wrapper" style="min-height: 263px;">
            <div class="container-fluid">
              <div class="card-block">
                <% if notice %>
                <p class="alert alert-success"><%= notice %></p>
                <% end %>
                <% if alert %>
                <p class="alert alert-danger"><%= alert %></p>
                <% end %>
                <%= yield %>
              </div>
            </div>
          </div>
      </div>
    </body>

    <footer class="footer text-center">
      © <%= Time.now.year %> SECURITY WEBSITE UECE BANK LTDA - BETA 2.0.0
    </footer>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </html>

<%else%>
  <html style="height: 100%;margin: 0;background-image: url(/back2.jpg);height: 100%;background-position: center;background-repeat: no-repeat;background-size: cover;top:0%;">
    <head>
      <title>UECE BANK</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>

    <body style="background: #54657a00;">
        <div class="login">
          <div class="bg">
            <%= yield %>
          </div>
        </div>
    </body>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </html>
<%end%>